name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  check_machines:
    name: Check machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
          echo "Commit SHA": ${{ github.sha }}
          echo "This was deployed via an action $GITHUB_EVENT_NAME from the $GITHUB_REPOSITORY repo"
          echo "The specific commit was $GITHUB_SHA"
        shell: bash
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1' # The Go version to download (if necessary) and use.
      - uses: superfly/flyctl@feat/add-label-to-images
      - run: go run . deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
